on:
  push:
    branches:
      - master
  release:
    types:
      - created
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_cpu: [x86]
    env:
      EXTRA_FLAGS: 'target_cpu="${{ matrix.target_cpu }}"'
    steps:
      - uses: actions/download-artifact@v2
      - run: ls -R
