on:
  push:
    branches:
      - master
  release:
    types:
      - created
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_cpu: [x86]
    env:
      EXTRA_FLAGS: 'target_cpu="${{ matrix.target_cpu }}"'
    steps:
      - run: dpkg -S /lib32/libc.so.6
      - run: dpkg -l libc6-*
