on:
  push:
    branches:
      - master
  release:
    types:
      - created
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_cpu: [x86]
    env:
      EXTRA_FLAGS: 'target_cpu="${{ matrix.target_cpu }}"'
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt update && sudo apt install ninja-build pkg-config libnss3-dev qemu-user
      - name: Configure
        working-directory: src
        run: ./get-clang.sh
      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: src/out/sysroot-build/sid/debian_sid_i386_sysroot.tar.xz
