on:
  push:
    branches:
      - master
  release:
    types:
      - created
jobs:
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [arm64, arm]
    env:
      EXTRA_FLAGS: 'target_cpu="${{ matrix.arch }}"'
    steps:
      - uses: actions/checkout@v2
      - run: brew install ninja
      - run: ./get-clang.sh
        working-directory: src
      - run: ./build.sh
        working-directory: src
      - run: ./tests/basic.sh src/out/Release/naive
  win:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        arch: [arm]
    env:
      EXTRA_FLAGS: 'target_cpu="${{ matrix.arch }}"'
    steps:
      - uses: actions/checkout@v2
      - run: cinst ninja
      - run: ./get-clang.sh
        working-directory: src
      - run: ./build.sh
        working-directory: src
      - run: ./tests/basic.sh src/out/Release/naive
        if: ${{ matrix.arch != 'arm' }}
