on:
  push:
    branches:
      - master
  release:
    types:
      - created
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_cpu: [x86]
    env:
      EXTRA_FLAGS: 'target_cpu="${{ matrix.target_cpu }}"'
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt update && sudo apt install ninja-build pkg-config libnss3-dev qemu-user strace
      - run: ./get-clang.sh
        working-directory: src
      - run: ./build.sh
        working-directory: src
      - run: strace -f qemu-i386 -L src/out/sysroot-build/sid/sid_i386_staging src/out/Release/naive --help
